version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: loan_simulator_api_development
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/loan_simulator_api_development
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/loan_simulator_api_development
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
