{
  "openapi": "3.0.1",
  "info": {
    "title": "API de Simulação de Empréstimos",
    "version": "v1",
    "description": "API para simular e gerenciar empréstimos",
    "contact": {
      "name": "Priscila Cabral",
      "email": "priscilacabral.dev@gmail.com"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "local"
    }
  ],
  "components": {
    "schemas": {
      "error": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "errors": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Loan Simulators",
      "description": "Operações relacionadas a simulações de créditos"
    },
    {
      "name": "Customers",
      "description": "Operações relacionadas a clientes"
    }
  ],
  "paths": {
    "/api/v1/customers": {
      "get": {
        "summary": "list customers",
        "tags": [
          "Customers"
        ],
        "parameters": [
          {
            "name": "include_deleted",
            "in": "query",
            "required": false,
            "description": "Include soft deleted customers",
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "customers": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "document_number": {
                            "type": "string"
                          },
                          "phone": {
                            "type": "string",
                            "nullable": true
                          },
                          "address": {
                            "type": "string",
                            "nullable": true
                          },
                          "city": {
                            "type": "string",
                            "nullable": true
                          },
                          "state": {
                            "type": "string",
                            "nullable": true
                          },
                          "zip_code": {
                            "type": "string",
                            "nullable": true
                          },
                          "birthdate": {
                            "type": "string",
                            "format": "date"
                          },
                          "income": {
                            "type": "string",
                            "format": "decimal"
                          },
                          "deleted_at": {
                            "type": "string",
                            "format": "date-time",
                            "nullable": true
                          },
                          "created_at": {
                            "type": "string",
                            "format": "date-time"
                          },
                          "updated_at": {
                            "type": "string",
                            "format": "date-time"
                          }
                        },
                        "required": [
                          "id",
                          "name",
                          "email",
                          "document_number",
                          "birthdate",
                          "income",
                          "created_at",
                          "updated_at"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "create customer",
        "tags": [
          "Customers"
        ],
        "parameters": [],
        "responses": {
          "201": {
            "description": "created"
          },
          "422": {
            "description": "unprocessable entity",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "object",
                      "additionalProperties": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "customer": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "document_number": {
                        "type": "string"
                      },
                      "phone": {
                        "type": "string"
                      },
                      "address": {
                        "type": "string"
                      },
                      "city": {
                        "type": "string"
                      },
                      "state": {
                        "type": "string"
                      },
                      "zip_code": {
                        "type": "string"
                      },
                      "birthdate": {
                        "type": "string",
                        "format": "date"
                      },
                      "income": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "name",
                      "email",
                      "document_number",
                      "birthdate",
                      "income"
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/customers/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "integer"
          }
        },
        {
          "name": "include_deleted",
          "in": "query",
          "required": false,
          "schema": {
            "type": "boolean"
          }
        }
      ],
      "get": {
        "summary": "show customer",
        "tags": [
          "Customers"
        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "document_number": {
                      "type": "string"
                    },
                    "phone": {
                      "type": "string",
                      "nullable": true
                    },
                    "address": {
                      "type": "string",
                      "nullable": true
                    },
                    "city": {
                      "type": "string",
                      "nullable": true
                    },
                    "state": {
                      "type": "string",
                      "nullable": true
                    },
                    "zip_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "birthdate": {
                      "type": "string",
                      "format": "date"
                    },
                    "income": {
                      "type": "string",
                      "format": "decimal"
                    },
                    "deleted_at": {
                      "type": "string",
                      "format": "date-time",
                      "nullable": true
                    },
                    "created_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "updated_at": {
                      "type": "string",
                      "format": "date-time"
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "email",
                    "document_number",
                    "birthdate",
                    "income",
                    "created_at",
                    "updated_at"
                  ]
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "update customer",
        "tags": [
          "Customers"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful"
          },
          "422": {
            "description": "unprocessable entity",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "object",
                      "additionalProperties": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "customer": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "phone": {
                        "type": "string"
                      },
                      "address": {
                        "type": "string"
                      },
                      "city": {
                        "type": "string"
                      },
                      "state": {
                        "type": "string"
                      },
                      "zip_code": {
                        "type": "string"
                      },
                      "income": {
                        "type": "number"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete customer",
        "tags": [
          "Customers"
        ],
        "responses": {
          "204": {
            "description": "no content"
          },
          "404": {
            "description": "not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/loan_simulators": {
      "get": {
        "summary": "Listar simulações de crédito",
        "tags": [
          "Loan Simulators"
        ],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Número da página",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "per_page",
            "in": "query",
            "description": "Itens por página",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "loan_simulators": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "customer_id": {
                            "type": "integer"
                          },
                          "requested_amount": {
                            "type": "string"
                          },
                          "term_in_months": {
                            "type": "integer"
                          },
                          "interest_rate": {
                            "type": "string"
                          },
                          "monthly_payment": {
                            "type": [
                              "string",
                              "null"
                            ]
                          },
                          "total_payment": {
                            "type": [
                              "string",
                              "null"
                            ]
                          },
                          "total_interest": {
                            "type": [
                              "string",
                              "null"
                            ]
                          },
                          "status": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "id",
                          "customer_id",
                          "requested_amount",
                          "term_in_months",
                          "status"
                        ]
                      }
                    },
                    "pagination": {
                      "type": "object",
                      "properties": {
                        "current_page": {
                          "type": "integer"
                        },
                        "total_pages": {
                          "type": "integer"
                        },
                        "total_count": {
                          "type": "integer"
                        }
                      }
                    }
                  },
                  "required": [
                    "loan_simulators",
                    "pagination"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/loan_simulators/{id}": {
      "get": {
        "summary": "Mostrar simulações de crédito",
        "tags": [
          "Loan Simulators"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID de simulação de empréstimo",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "customer_id": {
                      "type": "integer"
                    },
                    "requested_amount": {
                      "type": "string"
                    },
                    "term_in_months": {
                      "type": "integer"
                    },
                    "interest_rate": {
                      "type": "string"
                    },
                    "monthly_payment": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "total_payment": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "total_interest": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "status": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    },
                    "deleted_at": {
                      "type": [
                        "string",
                        "null"
                      ]
                    }
                  },
                  "required": [
                    "id",
                    "customer_id",
                    "requested_amount",
                    "term_in_months",
                    "status"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    }
  }
}